# Generated by Django 5.2.7 on 2026-07-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promotion",
            old_name="discount_percentage",
            new_name="discount",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="active",
        ),
        migrations.AlterField(
            model_name="promotion",
            name="description",
            field=models.TextField(),
        ),
    ]
