# Generated by Django 5.2.7 on 2026-07-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Customer", "Customer"),
                            ("Restaurant", "Restaurant"),
                            ("Admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CustomerProfile",
        ),
    ]
